// <auto-generated />
namespace AuctioNUS.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class deviceID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deviceID));
        
        string IMigrationMetadata.Id
        {
            get { return "201307232153385_deviceID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
